version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"  # Root folder where package.json is
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
