name: Build & Release Electron App

on:
  push:
    tags:
      - 'v*'  # Trigger only on version tags like v1.0.0

jobs:
  release:
    runs-on: macos-latest  # Only macOS can build .dmg

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Vite app
        run: npm run build

      - name: Package Electron app
        run: npm run dist

      - name: Upload release to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: release/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
